CREATE TABLE voice_settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL UNIQUE,
  accent ENUM('US_ENGLISH', 'UK_ENGLISH', 'AUSTRALIAN_ENGLISH', 'INDIAN_ENGLISH') NOT NULL DEFAULT 'US_ENGLISH',
  voice_gender ENUM('MALE', 'FEMALE') NOT NULL DEFAULT 'MALE',
  speech_speed DECIMAL(3, 2) NOT NULL DEFAULT 1.00 CHECK (speech_speed >= 0.50 AND speech_speed <= 2.00),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
